### ISSUE TITLE
Part 2의 3강에서 state transition matrix 관련 질문 드립니다.

### ISSUE THREAD

**Issue by KimRass** [Junyoungpark/ReinforcementLearningAtoZ#6]
안녕하세요. 패스트캠퍼스 강의 잘 듣고 있습니다.

질문을 어디다 드려야 할지 모르겠어서 여기에 남깁니다.

GridworldEnv class에서

![image](https://user-images.githubusercontent.com/67457712/119519640-8f3f8600-bdb4-11eb-8815-90df4221f548.png)

가 나오는데, P[0, 15, 15]가 1인 것이 아니라 P[0, 15, 11]이 0이 맞는 것 아닌가요?

**Comment by Junyoungpark** [comment]
아 제 강의에서 설명이 부족했나보네요. 그 렉쳐 노트에 가장앞을 보시면 "T" 라고 표시된 마크가 보이시나요?
===========
T  x  o  o
o  o  o  o
o  o  o  o
o  o  o  T
===========
우리가 만든 환경에서 0 번째 상태와 15번째 상태는 종결상태 (Terminal state) 입니다. MDP정의상 (혹은 RL에서 계산의 용의성을 위해서) 종결상태에 진입하면, 
그 다음 상태는, 어떤 action 이든 상관없이, 해당 종결상태가 됩니다. 말씀해주신 사례는 딱 그 예시인데요, 15번째 -- 즉 우측하단의 종결상태 -- 에 진입하였기 때문에
어느 action 이든 상관없이 다음 상태가 15가 되며, 이걸 tensor 로 표현할 때 P[0,15,15] = 1.0 이 됩니다.

질문에 대답이 되었을까요?

**Comment by Junyoungpark** [comment]
아 제 강의에서 설명이 부족했나보네요. 그 렉쳐 노트에 가장앞을 보시면 "T" 라고 표시된 마크가 보이시나요?

T  x  o  o
o  o  o  o
o  o  o  o
o  o  o  T

우리가 만든 환경에서 0 번째 상태와 15번째 상태는 종결상태 (Terminal state) 입니다. MDP정의상 (혹은 RL에서 계산의 용의성을 위해서) 종결상태에 진입하면, 
그 다음 상태는, 어떤 action 이든 상관없이, 해당 종결상태가 됩니다. 말씀해주신 사례는 딱 그 예시인데요, 15번째 -- 즉 우측하단의 종결상태 -- 에 진입하였기 때문에
어느 action 이든 상관없이 다음 상태가 15가 되며, 이걸 tensor 로 표현할 때 P[0,15,15] = 1.0 이 됩니다.

질문에 대답이 되었을까요?
