### ISSUE TITLE
gym version에 따른 import 에러

### ISSUE THREAD

**Issue by heomangab** [Junyoungpark/ReinforcementLearningAtoZ#9]
현재 gym을 설치하면 0.22.0 버전을 설치하는데요

그러면 [src.common.gridworld.py](https://github.com/Junyoungpark/ReinforcementLearningAtoZ/blob/master/src/common/gridworld.py)의 4번째 줄인

from gym.envs.toy_text import discrete에서 에러가 납니다ㅠㅠ

버전을 0.21으로 낮추면 해결되는데요, 말씀드려야될 것 같아서 이슈에 올려요!!

**Comment by Junyoungpark** [comment]
제보 감사합니다. 빠른 시일내에 수정코드를 배포할수 있도록 하겠습니다. 
그 동안엔 readme 에 gym을 0.21버전의 사용을 명기하겠습니다.

**Comment by Junyoungpark** [comment]
늦었지만 해당 문제를 고쳤습니다. 의견 남겨주셔서 감사합니다.
